# Generated by Django 5.1.4 on 2024-12-17 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message="Le nom d'utilisateur ne peut contenir que des lettres, chiffres, underscores (_) et espaces.", regex='^[a-zA-Z0-9_ ]+$')]),
        ),
    ]
