# Generated by Django 5.1.4 on 2025-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
