# Generated by Django 5.1.6 on 2025-02-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_apikey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'user')},
        ),
    ]
